### ISSUE TITLE
Implement NGINX Load Balancer for Django Microservices with Docker

### ISSUE THREAD

**Issue by monster0318** [monster0318/LB-Microservice-Django-Docker-#8]
#### Description

To enable scalable architecture and proper service routing, this issue will set up **NGINX as a reverse proxy and load balancer** for multiple Django microservices running in Docker containers.

This setup will:

* Load balance traffic between multiple Django service instances
* Use Docker Compose to orchestrate services
* Forward requests through NGINX
* Support horizontal scaling of Django containers

---

#### Tasks:

* [ ] Create multiple Django containers using the same image
* [ ] Write `nginx.conf` to define upstream services
* [ ] Add Docker Compose service for NGINX
* [ ] Configure NGINX to route requests to Django containers
* [ ] Expose NGINX on port 80 as the entrypoint to the system

---

#### Example Code Snippet:

```nginx
# nginx.conf
upstream django_backend {
    server django1:8000;
    server django2:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://django_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

```yaml
# docker-compose.yml
version: '3'
services:
  django1:
    build: .
    container_name: django1
    expose:
      - "8000"

  django2:
    build: .
    container_name: django2
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django1
      - django2
```

---

#### Benefits:

* Provides high availability and traffic distribution
* Abstracts direct access to backend services
* Enables easy container scaling (`docker-compose up --scale django=3`)
