### ISSUE TITLE
Dockerized Django microservice fails to connect to PostgreSQL container on startup

### ISSUE THREAD

**Issue by monster0318** [monster0318/LB-Microservice-Django-Docker-#9]
### Description:

When starting the Docker containers with `docker-compose up`, the Django microservice crashes with a database connection error because it attempts to connect to the PostgreSQL service before the database is ready.

#### Steps to reproduce:

1. Clone the repo and run `docker-compose up` to start all services.
2. Observe the Django container logs for errors.

#### Expected behavior:

Django microservice should wait until the PostgreSQL container is fully ready and then connect without errors.

#### Actual behavior:

Django microservice logs show connection errors similar to:

```plaintext
django.db.utils.OperationalError: could not connect to server: Connection refused
    Is the server running on host "db" (172.18.0.2) and accepting
    TCP/IP connections on port 5432?
```

#### Relevant `docker-compose.yml` snippet:

```yaml
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
```

#### Cause:

`depends_on` only waits for the container to start, but does **not** wait for the PostgreSQL service to be ready to accept connections.

#### Suggested fix:

Implement a wait-for script or health check that delays Django startup until PostgreSQL is ready.

Example solution using [`[wait-for-it.sh](https://github.com/vishnubob/wait-for-it)`](https://github.com/vishnubob/wait-for-it):

1. Add `wait-for-it.sh` script to the Django container.
2. Change the `command` in `docker-compose.yml`:

```yaml
command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
```

#### Additional tips:

* Alternatively, implement retry logic in Django’s database connection settings.
* Use Docker healthchecks to signal readiness.

#### Environment:

* Docker version: 20.x+
* Docker Compose version: 1.29+
* Django version: 3.x or 4.x
* PostgreSQL version: 13+
* OS: Ubuntu 20.04 / macOS / Windows 10

---
